name := `cat build/CMakeCache.txt | grep CMAKE_PROJECT_NAME | awk -F '=' '{print $2}'` 

init:
  cmake -B build

init_windows:
  cmake -B build -DCMAKE_TOOLCHAIN_FILE=./toolchain.cmake

build:
  just init
  cmake --build build -j 8

debug:
  cmake -B build -DCMAKE_BUILD_TYPE=Debug
  cmake --build build -j 8

run:
  just build
  ./build/{{name}}

run_windows:
  just build
  ./build/{{name}}.exe

clean:
  rm -rf build
